// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhDXlxz0Hp7eWj6snrFzHplikTEPheKUs',
    appId: '1:607435207157:web:29f0c6e4fbc693642ff0bc',
    messagingSenderId: '607435207157',
    projectId: 'caca-73631',
    authDomain: 'caca-73631.firebaseapp.com',
    storageBucket: 'caca-73631.appspot.com',
    measurementId: 'G-WC29R8VZNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_tVM3YTb1POlt75gW-6PhEFAVANR1WCE',
    appId: '1:607435207157:android:84f6fa32cab7fa022ff0bc',
    messagingSenderId: '607435207157',
    projectId: 'caca-73631',
    storageBucket: 'caca-73631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTv-iIQUEO6iSMlaKklN-WQADD5fMHhk',
    appId: '1:607435207157:ios:231bffe4ebe43c072ff0bc',
    messagingSenderId: '607435207157',
    projectId: 'caca-73631',
    storageBucket: 'caca-73631.appspot.com',
    iosBundleId: 'com.example.caca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTv-iIQUEO6iSMlaKklN-WQADD5fMHhk',
    appId: '1:607435207157:ios:231bffe4ebe43c072ff0bc',
    messagingSenderId: '607435207157',
    projectId: 'caca-73631',
    storageBucket: 'caca-73631.appspot.com',
    iosBundleId: 'com.example.caca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhDXlxz0Hp7eWj6snrFzHplikTEPheKUs',
    appId: '1:607435207157:web:c278d2fcf51bc0562ff0bc',
    messagingSenderId: '607435207157',
    projectId: 'caca-73631',
    authDomain: 'caca-73631.firebaseapp.com',
    storageBucket: 'caca-73631.appspot.com',
    measurementId: 'G-H8Z89ECT3Z',
  );

}